# Libraries

In [ ]:
import pandas as pd
import sys
import os
import torch
import torch.nn as nn

sys.path.append(os.path.abspath(os.pardir))

from src.data_processing import *

# Dataset Processing

In [37]:
dataset_path = os.path.join('..','datasets','Philippine Fake News Corpus.csv')
df = pd.read_csv(dataset_path)
df.head()

,Headline,Content,Authors,Date,URL,Brand,Label
0,PH ranks 2nd in Asia-Pacific in deaths due to ...,Pollution caused by traditional cooking fuel i...,['Philippine Daily Inquirer'],NaN,https://newsinfo.inquirer.net/987262/ph-ranks-...,Inquirer,Credible
1,"Aguirre, PCSO chief deny plotting to kill ‘Ato...",Justice Secretary Vitaliano Aguirre 2nd and Ph...,['Jomar Canlas'],2017-04-28 20:12:54+00:00,https://www.manilatimes.net/aguirre-pcso-chief...,Manila Times,Credible
2,Duterte says charges vs ex-President will fail,President Rodrigo Duterte on Monday night desc...,['Christine O. Avendaño'],NaN,https://newsinfo.inquirer.net/914727/duterte-s...,Inquirer,Credible
3,Group warns BFAR on law enforcement fund,THE militant fisher folk group Pambansang Laka...,['Neil Alcober'],2017-08-12 19:54:48+00:00,https://www.manilatimes.net/group-warns-bfar-l...,Manila Times,Credible
4,Solon asks Duterte for jet ski to Panatag,Magdalo Rep. Gary Alejano is willing to lead t...,['Dj Yap'],NaN,https://newsinfo.inquirer.net/882744/solon-ask...,Inquirer,Credible

In [39]:
news_df = df[['Brand','Content','Label']].copy()
news_df['Feature'] = news_df['Brand'] + ': ' + news_df['Content']
news_df = news_df[['Feature','Label']]
news_df.head()

                                             Feature     Label
0  Inquirer: Pollution caused by traditional cook...  Credible
1  Manila Times: Justice Secretary Vitaliano Agui...  Credible
2  Inquirer: President Rodrigo Duterte on Monday ...  Credible
3  Manila Times: THE militant fisher folk group P...  Credible
4  Inquirer: Magdalo Rep. Gary Alejano is willing...  Credible

In [41]:
train, test = process_data(news_df, 'Feature','Label', random_state = 42)
display(train)
display(test)

                                                 Feature  Label
13271  [397, 398, 7972, 5154, 8, 2589, 3706, 5252, 10...      1
7552   [542, 7972, 1242, 2722, 4, 1841, 2654, 6506, 7...      0
11813  [542, 7972, 196, 7075, 29, 1582, 7953, 7926, 5...      0
20905  [397, 398, 7972, 220, 4354, 137, 7964, 7934, 1...      1
15973  [397, 398, 7972, 220, 4126, 73, 6316, 790, 795...      1
...                                                  ...    ...
21575  [311, 967, 7972, 220, 2905, 2615, 27, 8, 295, ...      0
5390   [311, 846, 7972, 220, 3219, 2805, 1639, 7926, ...      0
860    [542, 7972, 220, 1133, 65, 3940, 137, 5609, 79...      0
15795  [1716, 1715, 7972, 1055, 1063, 5485, 209, 65, ...      1
23654  [311, 846, 7972, 3757, 8, 1146, 27, 708, 175, ...      0

[23683 rows x 2 columns]

                                                 Feature  Label
27664  [4020, 4110, 295, 7972, 2129, 1433, 1346, 7941...      1
28750  [1716, 1715, 7972, 716, 150, 1523, 73, 64, 566...      1
5115   [397, 398, 7972, 7419, 358, 76, 426, 6153, 65,...      1
12401  [542, 7972, 220, 1475, 133, 8, 774, 27, 1148, ...      0
17123  [397, 398, 7972, 7233, 926, 7941, 220, 397, 39...      1
...                                                  ...    ...
9547   [4020, 4110, 295, 7972, 220, 2800, 201, 853, 3...      1
2090   [542, 7972, 57, 2330, 205, 2467, 63, 1366, 450...      0
18717  [397, 398, 7972, 7419, 347, 1290, 466, 5836, 7...      1
8158   [1716, 1715, 7972, 57, 420, 190, 4242, 5202, 7...      1
23579  [311, 967, 7972, 1582, 65, 1388, 1329, 49, 798...      0

[5921 rows x 2 columns]

# Model Architecture

In [ ]:
class FakeNewsDetector(nn.Module):
    def __init__(self):
        self.embed = nn.Embedding()
        self.conv1d = nn.Conv1d()
        self.pool1d = nn.MaxPool1d()
        self.flat = nn.Flatten()
        self.fc = nn.Linear()
        
    def forward(self, x):
        ...
        return x